--- #YAML:1.0
name:                HTML-Element-Library
version:             4.2.b
abstract:            ~
license:             ~
author:              
    - Terrence Brannon <tbone@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Array::Group:                  1
    File::Slurp:                   9999.06
    HTML::FillInForm:              0
    HTML::PrettyPrinter:           0.03
    HTML::Tree:                    3.19
    List::MoreUtils:               0.09
    List::Rotation::Cycle:         1.003
    Moose:                         0
    Params::Validate:              0.8
    Scalar::Listify:               0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
