# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Element-Library
version:      0.06
version_from: lib/HTML/Element/Library.pm
installdirs:  site
requires:
    File::Slurp:                   9999.06
    HTML::PrettyPrinter:           0.03
    HTML::Tree:                    3.18
    List::MoreUtils:               0.09
    List::Rotation::Cycle:         1.003
    Scalar::Listify:               0.02
    Set::Array:                    0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
